#!/usr/bin/env python3
"""Generate lexicon/rust.md Types and Functions tables from rustdoc JSON.

Usage:
    # First generate JSON (requires nightly):
    RUSTDOCFLAGS="-Z unstable-options --output-format json" \
        cargo +nightly doc --no-deps -p dash-sdk -p dpp -p rs-dapi-client -p dapi-grpc

    # Then run this script:
    python3 scripts/gen-rust-lexicon.py <target-doc-dir> [--patterns lexicon/rust-patterns.md]

Outputs to stdout. Append --patterns to concatenate a hand-maintained
Patterns/Examples file after the auto-generated tables.

The script reads rustdoc JSON for dash-sdk, dpp, rs-dapi-client, and dapi-grpc,
extracts all public types and functions, and outputs a markdown lexicon table.

Filtering: internal consensus errors and state transition field constants are
excluded to keep the lexicon focused on SDK-facing API surface.
"""
import json
import os
import sys
from collections import defaultdict
from datetime import date

PACKAGES = {
    "dash_sdk": "rs-sdk",
    "dpp": "rs-dpp",
    "rs_dapi_client": "rs-dapi-client",
    "dapi_grpc": "dapi-grpc",
}

# Paths to exclude (internal implementation details)
SKIP_PATHS = [
    "errors/consensus",
]

SECTION_MAP = {
    "struct": "Types",
    "enum": "Types",
    "trait": "Types",
    "type_alias": "Types",
    "function": "Functions",
}

KIND_LABELS = {
    "struct": "struct",
    "enum": "enum",
    "trait": "trait",
    "type_alias": "type",
    "function": "fn",
}


def load_items(json_path, pkg_label):
    with open(json_path) as f:
        data = json.load(f)

    items = []
    for item in data["index"].values():
        inner = item.get("inner", {})
        if not isinstance(inner, dict):
            continue
        kind = next(iter(inner))
        if kind not in SECTION_MAP:
            continue
        if item.get("visibility") != "public" or item.get("crate_id") != 0:
            continue

        span = item.get("span") or {}
        filename = span.get("filename", "")

        if any(skip in filename for skip in SKIP_PATHS):
            continue

        name = item.get("name", "?")
        docs = (item.get("docs") or "").split("\n")[0].strip()
        if len(docs) > 120:
            docs = docs[:117] + "..."

        line = span.get("begin", [0])[0]
        src = ""
        if filename.startswith("packages/"):
            src = f"[P:{filename}#L{line}]"

        items.append(
            {
                "section": SECTION_MAP[kind],
                "kind": KIND_LABELS[kind],
                "name": name,
                "docs": docs,
                "src": src,
                "pkg": pkg_label,
            }
        )

    return items


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate Rust lexicon from rustdoc JSON")
    parser.add_argument("doc_dir", help="Path to cargo doc output directory containing .json files")
    parser.add_argument("--patterns", help="Path to hand-maintained patterns/examples markdown to append")
    args = parser.parse_args()

    doc_dir = args.doc_dir
    all_items = []

    for json_name, pkg_label in PACKAGES.items():
        path = os.path.join(doc_dir, f"{json_name}.json")
        if not os.path.exists(path):
            print(f"  SKIP {pkg_label}: {path} not found", file=sys.stderr)
            continue
        items = load_items(path, pkg_label)
        all_items.extend(items)
        print(f"  {pkg_label}: {len(items)} items", file=sys.stderr)

    sections = defaultdict(list)
    for item in all_items:
        sections[item["section"]].append(item)

    for section in sections.values():
        section.sort(key=lambda x: (x["kind"], x["name"]))

    today = date.today().isoformat()
    lines = [
        "# Rust SDK Lexicon",
        f"<!-- Auto-generated by update-lexicon. Do not edit. Updated: {today} -->",
        "<!-- Source: rustdoc JSON (dash-sdk, dpp, rs-dapi-client, dapi-grpc) -->",
        "",
    ]

    for section_name in ["Types", "Functions"]:
        items = sections.get(section_name, [])
        if not items:
            continue
        lines.append(f"## {section_name}")
        lines.append("| Kind | Keyword | Pkg | Description | Src |")
        lines.append("|------|---------|-----|-------------|-----|")
        for item in items:
            lines.append(
                f"| {item['kind']} | `{item['name']}` "
                f"| {item['pkg']} | {item['docs']} | {item['src']} |"
            )
        lines.append("")

    # Append hand-maintained patterns/examples if provided
    if args.patterns and os.path.exists(args.patterns):
        with open(args.patterns) as f:
            lines.append(f.read().rstrip())
        lines.append("")

    total = len(all_items)
    print(f"  Total: {total} entries", file=sys.stderr)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
